# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: surveygen
builds:
  - id: surveygen
    binary: surveygen
    main: main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

changelog:
  sort: desc

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macOS

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: guumaster
    name: surveygen

nfpms:
  - id: surveygen
    builds:
      - surveygen
    formats:
      - deb
    vendor: Guumaster
    homepage: https://github.com/guumaster/surveygen
    maintainer: guumaster <guuweb@gmail.com>
    description: manage your hosts file like a pro
